gesture-recognition:
  url-game: "https://offline-dino-game.firebaseapp.com/"

speech-to-image:
  engToImage :
    STAB_HOST : "grpc.stability.ai:443"
    STAB_KEY  : "sk-cHfjUwInF8Uuds4AS77mGm3HQWuwXkl5N64o6XwfxkKVcWRh"

  LIB :
    TRANSLATOR : "vinai/vinai-translate-vi2en"
    RECOGNIZER : "https://api-inference.huggingface.co/models/nguyenvulebinh/wav2vec2-base-vietnamese-250h"
    RECOGNIZER_KEY : "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"

style-transfer: 