instruction_text    : "Please select an operating mode"

modes               : 
  button1           : "Play game Subway Surfers"
  button2           : "Speech to image"
  button3           : "Style transfer"

size                : 
  default_btn_size  : [40, 40]
  img_btn_size      : [480, 200]
  img_size          : [970, 200]

img_path            : 
  QUIT_BTN          : "quit_button.png"
  SETTINGS_BTN      : "settings_button.png"
  MODE1_BTN         : "game_mode.png"
  MODE2_BTN         : "speech2image_mode.png"
  MODE3_BTN         : "style-transfer_mode.png"


